#pragma once
#include <esp_err.h>

#define GENERAL_OK ESP_OK
#define GENERAL_FAIL ESP_FAIL

#define GENERAL_ERR_NVS_BASE 0X10
#define GENERAL_ERR_NVS_NOT_FOUND (GENERAL_ERR_NVS_BASE + 0x01)

#define GENERAL_ERR_USER_BASE 0x20
#define GENERAL_USER_INVALID_ID (GENERAL_ERR_USER_BASE + 0x01)
#define GENERAL_USER_PASSWORD_ERROR (GENERAL_ERR_USER_BASE + 0X02)
#define GENERAL_USER_FULL (GENERAL_ERR_USER_BASE + 0x03)
#define GENERAL_DEL_INVALID_ID (GENERAL_ERR_USER_BASE + 0x04)

#define GENERAL_CONNECTION_BASE 0x30
#define GENERAL_CONNECTION_DICONNECT (GENERAL_CONNECTION_BASE + 0X01)

typedef esp_err_t GeneralErr;
#define IS_OK(X) ( X == GENERAL_OK )
